const { registerWindowIpc } = require('./app/window-ipc.cjs');
const { registerClipboardIpc } = require('./shared/clipboard-ipc.cjs');
const { registerTerminalIpc } = require('./features/terminal/ipc.cjs');
const { registerWorkspaceIpc } = require('./features/workspace/ipc.cjs');
const { createSshRuntime } = require('./features/ssh/runtime.cjs');
const { registerSshIpc } = require('./features/ssh/ipc.cjs');
const { registerFilesIpc } = require('./features/files/ipc.cjs');
const { createEditorGuard } = require('./features/files/editor-guard.cjs');
const { createGitRuntime } = require('./features/git/runtime.cjs');
const { registerGitIpc } = require('./features/git/ipc.cjs');
const { registerUpdatesIpc } = require('./features/updates/ipc.cjs');
const { registerAgentsIpc } = require('./features/agents/ipc.cjs');
const { registerDirectIpc } = require('./features/agents/direct-ipc.cjs');
const { CodexDirect } = require('./features/agents/codex-direct.cjs');
const { folderHistory, launchCommand } = require('./features/agents/launch.cjs');
const { setThumbnailer, isGeneratedImage } = require('./conversation.cjs');
const { registerNoticesIpc } = require('./features/notices/ipc.cjs');
const { registerVoiceIpc } = require('./features/voice/ipc.cjs');
const { createIpcAdapter } = require('./shared/ipc.cjs');
const { app, BrowserWindow, ipcMain, dialog, Tray, Menu, nativeImage, Notification, clipboard, shell, protocol, safeStorage, session: electronSession, net: electronNet } = require('electron');
// Pictures in the reading view (generated by Codex, or pasted with a message) travel as a JPEG at most 640 pixels
// wide; a small picture stays as it was.
const thumbnail = image => {
  if (image.isEmpty()) return null;
  if (image.getSize().width <= 640) return null;
  return `data:image/jpeg;base64,${image.resize({ width: 640, quality: 'good' }).toJPEG(86).toString('base64')}`;
};
setThumbnailer(file => { const image = nativeImage.createFromPath(file); return thumbnail(image) || (image.isEmpty() ? null : image.toDataURL()); },
  url => thumbnail(nativeImage.createFromDataURL(url)) || url);
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const { desktopGlassKind, desktopGlassOptions, applyDesktopGlass } = require('./desktop-glass.cjs');
const { execFile } = require('node:child_process');
const { execFileSync } = require('node:child_process');
const { pathToFileURL } = require('node:url');
const { randomUUID } = require('node:crypto');
const pty = require('node-pty');
const { WorkspaceStore } = require('./state.cjs');
const { createEventServer } = require('./events.cjs');
const { ProjectGit } = require('./project-git.cjs');
const { acceptShellEvent, SubmissionTracker, PromptMarkers, InputGate } = require('./terminal-input.cjs');
const { PromptQueue } = require('./prompt-queue.cjs');
const { createTerminalEnvironment } = require('./terminal-env.cjs');
const { adoptSystemProxy } = require('./system-proxy.cjs');
const { PreviewResources, resourceResponse } = require('./preview-resources.cjs');
const { createFileCards } = require('./features/files/file-cards.cjs');
const { UpdateManager, isInstalledBuild } = require('./updates.cjs');
const { getSSHInfo } = require('./ssh-config.cjs');
const { SSHAuthServer } = require('./ssh-auth.cjs');
const { RemoteConnection } = require('./remote-connection.cjs');
const { recentSession, resumeCommand, claudeResumeCommand } = require('./session-restore.cjs');
const { CodexActivityReader, monitorActivity } = require('./codex-activity.cjs');
const { TerminalTitleTracker } = require('./terminal-title.cjs');
const { FileOperations } = require('./file-operations.cjs');
const { ClipboardWrites } = require('./clipboard-writes.cjs');
const { VoiceManager } = require('./voice.cjs');
const { SpeechManager } = require('./speech.cjs');
const { summarizeTask } = require('./task-summary.cjs');
const { ActionLog, TranscriptTail, claudeRecord, codexRecord, skillDescription } = require('./agent-actions.cjs');
const { summarizeRound, claudeReply, codexReply } = require('./round-summary.cjs');
const { ConversationLog, claudeConversation, codexConversation } = require('./conversation.cjs');
const { conversationBatchDelay, pollAfterSubmission } = require('./conversation-timing.cjs');
const { listAgentCommands, isLocalAgentCommand } = require('./agent-commands.cjs');
const { claudeConfigDir, findClaudeSession, listClaudeSessions } = require('./claude-sessions.cjs');
const { modelSummary, listModels, connection, SecretStore, TARGETS: SUMMARY_TARGETS } = require('./summary-models.cjs');
const { AgentsManager, onPath } = require('./agents.cjs');
const DEFAULT_SHORTCUTS = require('./shortcuts.json');
const { windowsAppId, materializeIcon, repairShortcuts, refreshSearchIcons } = require('./windows-integration.cjs');
const { ZSH, findShell, linuxShell, prepareZshStartup, shellEnvironment, zshEnvironment, bashArguments, withoutAppImage, terminalLocale, loginShellPath, mergePath } = require('./zsh-terminal.cjs');

const root = path.join(__dirname, '..');
const integrationDir = app.isPackaged ? path.join(process.resourcesPath, 'integration') : path.join(root, 'integration');
const devUrl = !app.isPackaged ? process.env.AGENTRIX_DEV_URL : null;
if (process.env.AGENTRIX_DATA_DIR) app.setPath('userData', path.resolve(process.env.AGENTRIX_DATA_DIR));
else if (app.isPackaged) app.setPath('userData', path.join(app.getPath('appData'), 'Agentrix'));
else {
  // `npm run dev` / `npm start` run beside the installed app, often from one of its own terminals.
  const devProfile = path.join(app.getPath('appData'), 'Agentrix Dev');
  require('./dev-profile.cjs').seedDevProfile(path.join(app.getPath('appData'), 'Agentrix'), devProfile);
  app.setPath('userData', devProfile);
}
// Downloaded voice models are shared with the installed app instead of being fetched again for a dev profile.
const voiceDirectory = () => path.join(!app.isPackaged && !process.env.AGENTRIX_DATA_DIR ? path.join(app.getPath('appData'), 'Agentrix') : app.getPath('userData'), 'voice');
app.setName('Agentrix');
const installed = isInstalledBuild(app.isPackaged, process.execPath);
const appUserModelId = windowsAppId({ packaged: app.isPackaged, installed, profile: process.env.AGENTRIX_DATA_DIR });
if (process.platform === 'win32') app.setAppUserModelId(appUserModelId);
protocol.registerSchemesAsPrivileged([
  { scheme: 'agentrix', privileges: { standard: true, secure: true, supportFetchAPI: true } },
  { scheme: 'project-preview', privileges: { standard: true, secure: true, supportFetchAPI: true, corsEnabled: true } },
]);

const { translate } = require('./i18n.cjs');
// Text shown by the main process follows the language chosen in settings (Chinese source -> locales/en.json).
const t = (text, values) => translate(store?.settings.language, text, values);
let window, tray, store, eventServer, sshAuth, updateManager, quitting = false, updatesIpc;
const desktopGlassBackend = desktopGlassKind();
let desktopGlassWindow = false, desktopGlassActive = false;
const sessions = new Map();
const { setBranch, captureBranch, getBranch, forgetBranch, remoteBranch } = createGitRuntime({ getProjects: () => store.projects, execFile, broadcast });
const projectGit = new ProjectGit(id => remoteFor(id));
const startupErrors = new Map();
const restorePlans = new Map();
const previewResources = new PreviewResources({ remote: project => remoteFor(project.id) });
const capturePage = require('./features/files/capture-page.cjs').createPageCapture(BrowserWindow);
const fileCard = createFileCards({ previews: previewResources, capture: capturePage });
let stateTimer;
let runtimeDir;
const { prepareAskpass, cleanupAskpass } = createSshRuntime({ fs, execFileSync, tempDirectory: () => app.getPath('temp'), integrationDir });
let zshStartup;
let activeTerminal = null;
let activeFileTree = null;
let fileOperations, filesIpc;
let voiceManager, speechManager, summarySecrets;
let attentionTimer;
const { allowEditorClose, affectsEditor, getEditorFile, registerEditorIpc } = createEditorGuard({ getWindow: () => window, showWindow, send, randomUUID, dialog, t });
const clipboardWrites = new ClipboardWrites();
const powershellPath = path.join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'WindowsPowerShell', 'v1.0', 'powershell.exe');
const cmdPath = process.env.ComSpec || path.join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'cmd.exe');
function send(channel, data) { if (window && !window.isDestroyed()) window.webContents.send(channel, data); }
const agents = new AgentsManager({ onChange: state => send('agents:changed', state), translate: t });
function findProject(id) {
  if (typeof id !== 'string') throw new Error('无效的项目。');
  const project = store.findTerminal(id)?.project;
  if (!project) throw new Error('项目不存在。');
  return project;
}
function publicState() {
  return {
    projects: store.projects.map(p => {
      const terminals = terminalIds(p).map((id, index) => {
        const s = sessions.get(id);
        return { id, title: t('终端 {n}', { n: index + 1 }), shell: s?.shellKind || (p.kind === 'ssh' ? 'bash' : localShell().kind), sessionId: s?.sessionId || null, status: s?.status || 'stopped', codexActive: s?.codexActive || false, agent: s?.codexActive ? s.agent || 'codex' : null,
          agentStartedAt: s?.codexActive ? s.activitySince : null,
          codexActivity: s?.codexActivity || 'unknown', needsInput: s?.needsInput?.message || null, shellReady: !!s?.ready && !s?.inputDirty, codexAvailable: s?.codexAvailable ?? null,
          lastCompletedAt: s?.lastCompletedAt || null, error: s?.error || startupErrors.get(id) || null,
          // The step a working agent is on, for the card's one-line status; the full list is sent separately.
          action: s?.codexActive && s.codexActivity === 'working' ? briefAction(s.actions.current()) : null,
          // What the round was asked to do, in a few words, for the activity overview.
          task: s?.codexActive ? s.lastTask || '' : '',
          // The prompts sent and not finished yet: the ones being worked on, then the ones waiting.
          prompts: s?.codexActive ? s.promptQueue.list() : [],
          // Codex connected directly: no terminal; the reading view is the whole card, with the question or approval
          // Codex waits on and the model it runs.
          direct: !!s?.direct, card: s?.direct ? s.card || null : null, agentInfo: s?.direct ? { model: s.info?.model || '', effort: s.info?.effort || '' } : null };
      });
      const first = terminals[0];
      const activeCodex = terminals.filter(item => item.codexActive);
      const activity = activeCodex.some(item => item.codexActivity === 'working') ? 'working' : activeCodex.some(item => item.codexActivity === 'interrupted') ? 'interrupted' : activeCodex.length && activeCodex.every(item => item.codexActivity === 'complete') ? 'complete' : 'unknown';
      const status = activeCodex.length ? 'codex' : terminals.some(item => item.status === 'shell') ? 'shell' : terminals.some(item => item.status === 'starting') ? 'starting' : first.status;
      return {
        id: p.id, name: p.name, path: p.path, unread: p.unread, lastCompletedAt: p.lastCompletedAt,
        kind: p.kind || 'local', ssh: p.ssh || null,
        branch: getBranch(p.id) || '',
        terminals, sessionId: first.sessionId, status,
        codexActive: activeCodex.length > 0, codexActivity: activity, agent: activeCodex[0]?.agent || null,
        shellReady: first.shellReady, codexAvailable: first.codexAvailable,
        error: terminals.find(item => item.error)?.error || null,
        action: terminals.find(item => item.action)?.action || null,
      };
    }),
    settings: store.settings,
    desktopGlass: { supported: !!desktopGlassBackend, compatibility: desktopGlassBackend === 'windows-compat', active: desktopGlassActive, restart: store.settings.surface === 'glass' && store.settings.glassBackground === 'desktop' && !!desktopGlassBackend && !desktopGlassWindow, failed: desktopGlassWindow && !desktopGlassActive },
    warning: store.warning,
    platform: process.platform,
    // Linux: the shell new local terminals use and whether zsh is installed, for the choice in Settings.
    localShell: process.platform === 'linux' ? (({ kind, zsh }) => ({ kind, zsh }))(localShell()) : null,
    // In full screen the title bar slides away and returns when the pointer touches the top edge. The
    // desktop checks drive the title bar in full screen, so isolated test profiles keep it unless asked.
    autoHideTitlebar: !process.env.AGENTRIX_DATA_DIR || process.env.AGENTRIX_TEST_TITLEBAR === '1',
    version: app.getVersion(),
    // The usage guide opens on first use and after each update. Isolated test profiles skip it unless asked.
    guide: store.settings.guideVersion !== app.getVersion() && (!process.env.AGENTRIX_DATA_DIR || process.env.AGENTRIX_TEST_GUIDE === '1'),
  };
}

function terminalIds(project) {
  const extra = (project.terminals || []).map(item => item.id);
  return !sessions.has(project.id) && project.primaryTerminalClosed === true && extra.length ? extra : [project.id, ...extra];
}

function disposeProjectTerminals(project) {
  for (const id of [project.id, ...(project.terminals || []).map(item => item.id)]) { restorePlans.delete(id); disposeTerminal(id); startupErrors.delete(id); }
}
function updateIndicators() {
  const unread = store.projects.filter(p => p.unread > 0).length;
  if (window && !window.isDestroyed()) {
    window.setTitle(`${unread ? `(${unread}) ` : ''}${t('Agentrix')}`);
    if (!unread) window.flashFrame(false);
  }
  if (tray && !tray.isDestroyed()) {
    tray.setImage(trayImage(unread ? 'icon-alert.png' : 'icon.png'));
    tray.setToolTip(unread ? t('Agentrix · {count} 个项目待查看', { count: unread }) : t('Agentrix'));
  }
}
// The macOS menu bar draws an image at its own size in points, so the 256-pixel icon is scaled to fit it.
function trayImage(name) {
  const image = nativeImage.createFromPath(path.join(root, 'assets', name));
  return process.platform === 'darwin' ? image.resize({ width: 18, height: 18 }) : image;
}
// The same "Ctrl+Shift+F" form the window records (src/features/shortcuts/shortcuts.ts), from an Electron input event.
const SHORTCUT_KEYS = { Comma: ',', Period: '.', Slash: '/', Semicolon: ';', Quote: "'", BracketLeft: '[', BracketRight: ']', Backslash: '\\', Minus: '-', Equal: '=', Backquote: '`', Space: 'Space', Tab: 'Tab', Enter: 'Enter', NumpadEnter: 'Enter' };
function isAppShortcut(input) {
  const code = String(input.code || '');
  const key = /^Key[A-Z]$/.test(code) ? code.slice(3) : /^Digit\d$/.test(code) ? code.slice(5) : /^F([1-9]|1[0-2])$/.test(code) ? code : SHORTCUT_KEYS[code];
  if (!key) return false;
  const pressed = [input.control && 'Ctrl', input.alt && 'Alt', input.shift && 'Shift', key].filter(Boolean).join('+');
  return Object.values({ ...DEFAULT_SHORTCUTS, ...store.settings.shortcuts }).includes(pressed);
}

// macOS: the application menu gives ⌘Q, ⌘H and ⌘M their usual meaning. Copy and paste stay with the window's
// own key handling (before-input-event and the terminals), so there is no Edit menu to compete with it.
function macMenu() {
  return Menu.buildFromTemplate([
    { label: app.name, submenu: [
      { role: 'about', label: t('关于 Agentrix') }, { type: 'separator' },
      { role: 'hide', label: t('隐藏 Agentrix') }, { role: 'hideOthers', label: t('隐藏其他') }, { role: 'unhide', label: t('全部显示') }, { type: 'separator' },
      { label: t('退出 Agentrix'), accelerator: 'Command+Q', click: () => { showWindow(); requestQuit().catch(report); } },
    ] },
    { label: t('窗口'), submenu: [
      { role: 'minimize', label: t('最小化') }, { role: 'zoom', label: t('缩放') }, { role: 'togglefullscreen', label: t('切换全屏') },
      { type: 'separator' }, { label: t('关闭窗口'), accelerator: 'Command+W', click: () => window?.close() },
    ] },
  ]);
}

// Rebuilt when the language changes; Electron menus keep the labels they were built with.
function trayMenu() {
  if (!tray || tray.isDestroyed()) return;
  tray.setContextMenu(Menu.buildFromTemplate([
    { label: t('打开 Agentrix'), click: () => showWindow() },
    { type: 'separator' },
    { label: t('退出应用'), click: () => { showWindow(); requestQuit().catch(report); } },
  ]));
}

function broadcast() {
  clearTimeout(stateTimer);
  stateTimer = null;
  updateIndicators();
  send('workspace:changed', publicState());
}
function scheduleState() { if (!stateTimer) stateTimer = setTimeout(() => { stateTimer = null; broadcast(); }, 700); }
function report(error) { send('app:error', String(error?.message || error)); }

function showWindow(id) {
  if (!window || window.isDestroyed()) return;
  window.show();
  if (window.isMinimized()) window.restore();
  window.focus();
  if (id) send('project:focus', id);
}

// task: a short name for what the round worked on, from its prompt (empty when unknown).
// The agent's final words of the round are kept for the spoken summary; a new round forgets them.
function noteReply(s, reply) { if (reply?.reset) s.lastReply = ''; else if (reply?.text) s.lastReply = reply.text.slice(-8000); }
// A sentence saying what the round achieved, for the spoken notice, written the way the settings choose:
// not at all (fast, the default: the plain notice is spoken at once), by the round's own CLI, or by a
// cloud or local model over HTTP. Empty when nothing usable comes back; the plain notice is spoken then.
async function roundSummary(project, s) {
  const mode = store.settings.summary.mode;
  if (mode === 'fast' || !s || project.kind === 'ssh') return '';
  // Claude's transcript is read on a timer; read it to the end so the final reply is in hand.
  if (s.agent === 'claude') await s.activityMonitor?.poll();
  const material = { language: store.settings.language, task: s.lastTask || '', reply: s.lastReply || '' };
  if (!material.reply.trim()) return '';
  if (mode === 'agent') return summarizeRound({ agent: s.agent, ...material, directory: path.join(app.getPath('userData'), 'summaries') });
  return modelSummary({ target: mode, entry: store.settings.summary[mode], apiKey: summarySecrets.get(mode), ...material, fetcher: (url, options) => electronNet.fetch(url, options) });
}

// s: the terminal whose round finished, when known.
function notifyCompletion(project, task = '', s = null) {
  if (!window.isFocused()) {
    window.flashFrame(true); clearTimeout(attentionTimer);
    attentionTimer = setTimeout(() => { if (window && !window.isDestroyed()) window.flashFrame(false); }, 9000);
    attentionTimer.unref?.();
  }
  if (store.settings.notifications && Notification.isSupported()) {
    const note = new Notification({
      title: t('{name} · 本轮已完成', { name: project.name }),
      body: t('这一轮任务已结束，点击查看终端。'),
      icon: path.join(root, 'assets/icon-alert.png'),
      silent: !store.settings.sound,
    });
    note.on('click', () => showWindow(project.id));
    note.on('failed', () => {});
    note.show();
  }
  // Spoken with the system voice in the window, which knows the chosen language and phrase.
  if (store.settings.announce) {
    const notice = { projectId: project.id, name: project.name, task };
    roundSummary(project, s).catch(() => '').then(summary => send('completion:announce', summary ? { ...notice, summary } : notice));
  }
}

function briefAction(action) { return action ? { kind: action.kind, tool: action.tool, target: action.target, detail: action.detail, done: action.done, phrase: action.phrase, object: action.object } : null; }
// The agent's steps reach the window in small batches; after a long history is read at once (a resumed
// conversation) the whole list replaces what the window has.
function publishAction(s, change) {
  if (sessions.get(s.terminalId) !== s) return;
  (s.actionChanges ||= []).push(change);
  s.actionTimer ||= setTimeout(() => {
    const changes = s.actionChanges; s.actionChanges = []; s.actionTimer = null;
    if (sessions.get(s.terminalId) !== s) return;
    send('terminal:action', changes.length > 40 || changes.some(item => item.reset) ? { id: s.terminalId, list: s.actions.list } : { id: s.terminalId, changes: changes.map(item => item.action) });
    scheduleState();
  }, 120);
}
// The conversation for the reading view reaches the window the same way, in small batches.
function publishConversation(s, change) {
  if (sessions.get(s.terminalId) !== s || s.conversation.loading) return;
  (s.conversationChanges ||= []).push(change);
  const delay = conversationBatchDelay(s.conversationChanges);
  if (s.conversationTimer && s.conversationDelay === delay) return;
  clearTimeout(s.conversationTimer); s.conversationDelay = delay;
  s.conversationTimer = setTimeout(() => {
    const changes = s.conversationChanges; s.conversationChanges = []; s.conversationTimer = null; s.conversationDelay = null;
    if (sessions.get(s.terminalId) !== s || s.conversation.loading) return;
    // An answer streamed word by word puts the same entry many times in one batch: only its latest version goes.
    const latest = new Map();
    for (const item of changes) if (item.entry) latest.set(item.entry.id, item.entry);
    send('terminal:conversation', latest.size > 40 || changes.some(item => item.reset) ? { id: s.terminalId, list: s.conversation.snapshot() } : { id: s.terminalId, changes: [...latest.values()] });
  }, delay);
}
// A skill step names the skill; what the skill is for comes from its SKILL.md, a moment later.
function describeActions(s, cwd, actions) {
  for (const action of actions || []) {
    if (action.kind !== 'skill') continue;
    skillDescription(action.target, cwd, action.skillFile).then(description => { if (description) { action.description = description; s.actions.update(action); } }).catch(() => {});
  }
}
// Claude Code writes each tool call to its transcript; follow it while the session lasts.
function followClaude(project, s, event) {
  const file = typeof event.transcriptPath === 'string' ? path.resolve(event.transcriptPath) : '';
  const home = claudeConfigDir();
  if (!file || path.basename(file) !== `${event.sessionId}.jsonl` || !file.toLowerCase().startsWith(home.toLowerCase() + path.sep)) return;
  s.claudeFollowRequest = (s.claudeFollowRequest || 0) + 1;
  s.claudeSessionId = event.sessionId;
  if (s.claudeTranscript?.filename !== file) {
    s.claudeTranscript = new TranscriptTail(file, { onHistory: ready => {
      if (ready) s.conversation.endHistory();
      else { s.conversation.beginHistory(); s.actions.reset(); s.conversation.reset(); s.lastReply = ''; }
    } });
    s.activityMonitor?.stop();
    const tail = s.claudeTranscript;
    s.activityMonitor = monitorActivity(async () => { await tail.read(record => {
      if (sessions.get(s.terminalId) !== s || s.claudeTranscript !== tail) return;
      noteReply(s, claudeReply(record)); claudeConversation(s.conversation, record, project.path); describeActions(s, project.path, claudeRecord(s.actions, record, project.path));
    }); return null; }, () => {});
  } else void s.activityMonitor?.poll();
}

// Restores and the reading-view picker know the id before Claude emits its next prompt hook.
async function followClaudeSession(project, s, id) {
  const request = s.claudeFollowRequest = (s.claudeFollowRequest || 0) + 1;
  const cwd = store.findTerminal(s.terminalId)?.record.restore?.cwd || project.path;
  const file = await findClaudeSession(cwd, id);
  if (!file || sessions.get(s.terminalId) !== s || (!s.codexActive && s.claudeResumeId !== id) || (s.codexActive && s.agent !== 'claude')) return false;
  if (s.claudeFollowRequest !== request) return s.claudeSessionId === id && s.claudeTranscript?.filename === file;
  followClaude(project, s, { sessionId: id, transcriptPath: file });
  store.setRestore(s.terminalId, { threadId: id });
  await s.activityMonitor?.poll();
  return true;
}

// A round being worked on ends with a spoken notice: load the voice now, so it is ready by then.
const roundsWorking = () => [...sessions.values()].some(s => s.codexActive && s.codexActivity === 'working');
function warmSpeech() { if (store.settings.announce) speechManager?.warm().catch(() => {}); }

// One place turns an agent's turn state into lights and completion alerts, for Codex and Claude alike.
function applyActivity(project, s, snapshot) {
  if (sessions.get(s.terminalId) !== s || !s.codexActive) return;
  // Resumed history and a slow response from before a new submission
  // must not make newly running work look complete.
  if (snapshot.updatedAt < Math.max(s.activitySince, s.activityInputAt)) return;
  s.rootThreadId = snapshot.threadId;
  // Keep the last prompt that named some work; a bare "继续" or "continue" keeps the one before it.
  const task = summarizeTask(snapshot.prompt);
  if (task) s.lastTask = task;
  if (s.agent === 'codex') store.setRestore(s.terminalId, { threadId: snapshot.threadId });
  s.codexActivity = snapshot.state;
  if (snapshot.state === 'working') { store.expectCompletion(project.id); warmSpeech(); }
  if (['complete', 'interrupted'].includes(snapshot.state) && (s.agent === 'claude' || project.kind === 'ssh')) s.promptQueue.finish(snapshot.updatedAt);
  if (snapshot.state === 'complete' && snapshot.turnId) {
    s.lastCompletedAt = snapshot.updatedAt;
    if (!project.seenEvents.includes(`${snapshot.threadId}:${snapshot.turnId}`)) store.expectCompletion(project.id);
    if (store.complete(project.id, `${snapshot.threadId}:${snapshot.turnId}`, snapshot.updatedAt)) notifyCompletion(project, s.lastTask || '', s);
  } else if (snapshot.state === 'interrupted') store.expectCompletion(project.id, false);
  broadcast();
}

// Claude Code hooks: UserPromptSubmit -> working, Stop -> complete (integration/claude-hook.ps1). SessionStart -> the
// conversation Claude writes from now on: after /clear or /resume the reading view follows the new file at once.
// Notification -> attention while Claude waits for a permission answer in its own screen; that only
// sets the waiting indicator and never changes the round's lifecycle.
function claudeActivity(project, s, event) {
  if (!s.codexActive || s.agent !== 'claude' || !['working', 'complete', 'attention', 'session'].includes(event.state)) return;
  if (typeof event.sessionId !== 'string' || !/^[\w-]{1,100}$/.test(event.sessionId) || typeof event.eventId !== 'string' || event.eventId.length > 200) return;
  if (event.state === 'attention') { s.needsInput = { message: typeof event.message === 'string' ? event.message.slice(0, 300) : '', since: Date.now() }; broadcast(); return; }
  if (event.state === 'session') { followClaude(project, s, event); broadcast(); return; }
  // Claude Code runs its prompt hooks for some local slash commands (/context, /doctor, /compact) too. They open a screen
  // or print a line and no round follows, so they neither start a round nor end one; the card would stay "working".
  if (event.state === 'working') {
    s.claudeLocalCommand = typeof event.prompt === 'string' && isLocalAgentCommand('claude', event.prompt);
    if (s.claudeLocalCommand) return;
  } else if (event.state === 'complete' && s.claudeLocalCommand) { s.claudeLocalCommand = false; return; }
  s.needsInput = null;
  const turnId = event.eventId.slice(event.sessionId.length + 1);
  // Remember the conversation and whether its turn is still open, so a restart can resume it and continue.
  store.setRestore(s.terminalId, { threadId: event.sessionId, interrupted: event.state === 'working' });
  followClaude(project, s, event);
  if (event.state === 'complete') void s.activityMonitor?.poll().then(() => { if (sessions.get(s.terminalId) === s && s.codexActivity !== 'working') s.actions.settle(); });
  applyActivity(project, s, { threadId: event.sessionId, turnId: event.state === 'complete' ? turnId : null, state: event.state, updatedAt: Date.now(), prompt: typeof event.prompt === 'string' ? event.prompt.slice(0, 2000) : undefined });
}

function onEvent(event) {
  const s = sessions.get(event.projectId);
  if (!s || event.sessionKey !== s.sessionKey) return;
  const project = store.projects.find(p => p.id === s.projectId);
  if (!project) return;
  if (event.type === 'agent-activity') { claudeActivity(project, s, event); return; }
  if (event.type !== 'turn-complete' && !acceptShellEvent(s, event)) return;
  if (event.type === 'shell-ready' || event.type === 'shell-prompt') {
    s.needsInput = null;
    s.claudeResumeId = null; s.claudeFollowRequest = (s.claudeFollowRequest || 0) + 1;
    s.activityMonitor?.stop(); s.activityMonitor = null;
    s.codexActive = false; s.codexActivity = 'unknown'; s.reportedThreadId = null; s.promptQueue.reset();
    s.ready = event.type === 'shell-prompt';
    s.inputDirty = false;
    s.status = 'shell';
    s.codexAvailable = event.codexAvailable === true;
    s.claudeAvailable = event.claudeAvailable === true;
    if (typeof event.codexHome === 'string') s.codexHome = event.codexHome;
    if (!quitting && typeof event.cwd === 'string') store.setRestore(s.terminalId, { cwd: event.cwd });
  } else if (event.type === 'codex-started') {
    const claudeResumeId = event.agent === 'claude' ? s.claudeResumeId : null;
    const keepClaudeHistory = claudeResumeId && s.claudeSessionId === claudeResumeId && s.claudeTranscript;
    s.ready = false;
    s.codexActive = true;
    s.status = 'codex';
    s.error = null;
    s.submissions.reset();
    s.codexActivity = 'unknown'; s.activitySince = Date.now(); s.activityInputAt = 0;
    if (!keepClaudeHistory) { s.actions.reset(); s.conversation.reset(); s.claudeTranscript = null; s.claudeSessionId = null; }
    s.promptQueue.reset();
    s.agent = event.agent === 'claude' ? 'claude' : 'codex';
    if (!keepClaudeHistory) { s.activityMonitor?.stop(); s.activityMonitor = null; }
    // A terminal restores the agent it last ran. Switching agents drops the other one's conversation id.
    const previousAgent = store.findTerminal(s.terminalId)?.record.restore?.agent || 'codex';
    const agentRestore = { agent: s.agent, ...(previousAgent !== s.agent ? { threadId: null, interrupted: false } : {}) };
    if (s.agent === 'claude') {
      // Claude reports turns and its session id through hooks (claudeActivity).
      store.setRestore(s.terminalId, { terminal: true, codex: true, cwd: event.cwd, ...agentRestore });
      s.claudeResumeId = null;
      if (claudeResumeId) void followClaudeSession(project, s, claudeResumeId).catch(error => { s.error = String(error); broadcast(); });
      broadcast(); return;
    }
    store.setRestore(s.terminalId, agentRestore);
    const remoteSince = Number.isFinite(event.sentAt) ? event.sentAt : s.activitySince;
    s.activityMonitor?.stop();
    const reader = project.kind === 'ssh' ? null : new CodexActivityReader(event.cwd || project.path, event.codexHome || s.codexHome, s.activitySince, { threadId: () => s.reportedThreadId, requireBinding: () => (project.terminals?.length || 0) > 0,
      onHistory: ready => {
        if (ready) s.conversation.endHistory();
        else { s.conversation.beginHistory(); s.actions.reset(); s.conversation.reset(); s.lastReply = ''; }
      },
      onRecord: record => {
        noteReply(s, codexReply(record)); codexConversation(s.conversation, record, event.cwd || project.path); describeActions(s, event.cwd || project.path, codexRecord(s.actions, record, event.cwd || project.path));
        if (record?.type === 'event_msg' && ['task_complete', 'turn_completed', 'turn_aborted', 'turn_interrupted'].includes(record.payload?.type)) s.promptQueue.finish(Date.parse(record.timestamp) || Date.now());
      } });
    s.activityMonitor = monitorActivity(
      () => reader ? reader.read() : project.terminals?.length && !s.reportedThreadId ? Promise.resolve(null) : s.terminal.request('codex-status', { since: remoteSince, threadId: s.reportedThreadId }),
      snapshot => {
        if (!reader) snapshot = { ...snapshot, updatedAt: snapshot.updatedAt + s.activitySince - remoteSince };
        applyActivity(project, s, snapshot);
      },
    );
    store.setRestore(s.terminalId, { terminal: true, codex: true, cwd: event.cwd });
    // Unread completion is independent of session activity. It survives new turns.
  } else if (event.type === 'codex-exited') {
    s.needsInput = null;
    s.claudeResumeId = null; s.claudeFollowRequest = (s.claudeFollowRequest || 0) + 1;
    s.activityMonitor?.stop(); s.activityMonitor = null; s.codexActivity = 'unknown';
    s.ready = false;
    s.codexActive = false;
    s.status = 'shell';
    s.reportedThreadId = null;
    if (!quitting) store.setRestore(s.terminalId, { codex: false });
    const code = Number(event.exitCode);
    if (code && code !== 130 && code !== -1073741510) s.error = t('{agent} 已退出（代码 {code}），请查看终端输出。', { agent: s.agent === 'claude' ? 'Claude Code' : 'Codex', code });
  } else if (event.type === 'turn-complete') {
    // notify is inherited by child agents. It only requests a refresh; the
    // interactive parent's task lifecycle is the authority for completion.
    if (s.codexActive && (!s.rootThreadId || event.threadId === s.rootThreadId)) void s.activityMonitor?.poll();
    return;
  } else return;
  broadcast();
  if (event.type === 'shell-prompt') { void resumeAfterPrompt(project, s); launchAfterPrompt(project, s); }
}

// The agent chosen on a new project's card, typed at its terminal's first prompt (see agent:launch).
const launchPlans = new Map();
function launchAfterPrompt(project, session) {
  const plan = launchPlans.get(session.terminalId);
  if (!plan || !session.ready || session.inputDirty || session.codexActive) return;
  launchPlans.delete(session.terminalId);
  if (!(plan.agent === 'claude' ? session.claudeAvailable : session.codexAvailable)) {
    session.error = t('没有找到 {agent}，请在设置 › 编码助手中安装。', { agent: plan.agent === 'claude' ? 'Claude Code' : 'Codex' }); broadcast(); return;
  }
  session.ready = false;
  if (plan.agent === 'claude' && plan.threadId) { session.claudeResumeId = plan.threadId; void followClaudeSession(project, session, plan.threadId); }
  session.gate.afterPrompt(plan.command);
  broadcast();
}

async function resumeAfterPrompt(project, session) {
  const plan = restorePlans.get(session.terminalId);
  if (!plan || !session.ready || session.inputDirty) return;
  restorePlans.delete(session.terminalId);
  const restore = store.findTerminal(session.terminalId)?.record.restore;
  // Claude Code (local projects) resumes its own conversation, continuing an unfinished turn.
  if (restore?.agent === 'claude' && project.kind !== 'ssh') {
    if (!session.claudeAvailable || !plan.codex) return;
    try {
      const command = claudeResumeCommand(restore);
      if (sessions.get(session.terminalId) !== session || !session.ready || session.inputDirty || session.codexActive) return;
      store.expectCompletion(project.id, restore.interrupted === true);
      session.ready = false;
      session.claudeResumeId = restore.threadId || null;
      session.gate.afterPrompt(command);
      if (restore.threadId) await followClaudeSession(project, session, restore.threadId);
      broadcast();
    } catch (error) { session.error = `恢复会话失败：${error.message}`; broadcast(); }
    return;
  }
  if (!session.codexAvailable) return;
  try {
    const info = project.kind === 'ssh' ? await session.terminal.request('resume-info', { threadId: restore?.threadId }) : await recentSession(restore?.cwd || project.path, session.codexHome, restore?.threadId);
    // Legacy versions did not record which process owned a conversation. Open
    // that history, but do not submit work to a possibly still-running session.
    const remembered = info || (restore?.threadId ? { id: restore.threadId, state: 'unknown' } : null);
    const command = project.terminals?.length && !restore?.threadId ? 'codex\r' : resumeCommand(remembered && !plan.codex ? { ...remembered, state: 'unknown' } : remembered, plan.codex);
    if (command && sessions.get(session.terminalId) === session && session.ready && !session.inputDirty && !session.codexActive) {
      // Opening completed history is not new input. Only the automatic
      // continuation of interrupted work may produce another completion alert.
      store.expectCompletion(project.id, info?.state === 'interrupted' && plan.codex);
      session.ready = false;
      // The prompt has not been drawn yet; a remote shell asks no question to wait for.
      if (project.kind === 'ssh') session.gate.input(command); else session.gate.afterPrompt(command);
      broadcast();
    }
  } catch (error) { session.error = `恢复会话失败：${error.message}`; broadcast(); }
}

function remoteFor(id) {
  const project = findProject(id);
  const session = sessions.get(id)?.terminal.connected ? sessions.get(id) : [...sessions.values()].find(item => item.projectId === project.id && item.terminal.connected);
  if (project.kind !== 'ssh' || !session || session.terminal.closed) throw new Error('请先启动终端，连接 SSH 服务器。');
  return session.terminal;
}

// The local shell for a new terminal: PowerShell or Command Prompt on Windows, zsh on macOS, and on Linux
// Bash or zsh as chosen in Settings (the login shell's kind until one is chosen).
// Linux looks for the shells again whenever a terminal starts, so one installed meanwhile is used.
let linuxShells = null;
function localShell(fresh = false) {
  if (process.platform === 'darwin') return { kind: 'zsh', file: ZSH };
  if (process.platform !== 'linux') return { kind: store.settings.shell === 'cmd' ? 'cmd' : 'powershell', file: null };
  if (fresh || linuxShells?.choice !== store.settings.shell) linuxShells = { ...linuxShell(store.settings.shell), choice: store.settings.shell };
  return linuxShells;
}

function startTerminal(id) {
  const project = findProject(id);
  const old = sessions.get(id);
  if (old && old.status !== 'exited') return;
  if (old) disposeTerminal(id);
  if (!['win32', 'darwin', 'linux'].includes(process.platform)) throw new Error('此版本的终端集成面向 Windows 10/11、macOS 和 Linux。');
  if (project.kind !== 'ssh' && !fs.existsSync(project.path)) throw new Error('项目目录不存在，请重新添加。');
  const sessionId = randomUUID();
  const sessionKey = randomUUID();
  const startPath = restorePlans.get(id)?.cwd || store.findTerminal(id)?.record.restore?.cwd || project.path;
  // Local terminals use the shell chosen in settings (zsh on macOS); SSH projects always run Bash on the server.
  const shell = project.kind === 'ssh' ? { kind: 'bash', file: null } : localShell(true), shellKind = shell.kind;
  const bootstrapFile = ['powershell', 'cmd'].includes(shellKind) ? path.join(runtimeDir, `${sessionId}.json`) : null;
  if (bootstrapFile) fs.writeFileSync(bootstrapFile, JSON.stringify({
    projectId: id, projectPath: startPath, sessionKey, pipeName: eventServer.name,
    powershellPath, notifyPath: path.join(integrationDir, 'notify.ps1'), claudeHookPath: path.join(integrationDir, 'claude-hook.ps1'),
  }), { mode: 0o600 });
  let env = createTerminalEnvironment(withoutAppImage(process.env), bootstrapFile || '');
  // zsh and Bash learn where to report from their environment (integration/zsh-integration.zsh and
  // bash-integration.bash), and report through integration/agent-event.cjs run by this executable as Node.
  const local = project.kind !== 'ssh' && ['zsh', 'bash'].includes(shellKind);
  const integration = local && { folder: zshStartup, socket: eventServer.address, projectId: id, sessionKey, node: process.execPath,
    helper: path.join(integrationDir, 'agent-event.cjs'), startDir: startPath,
    // Every glibc since 2.35 has C.UTF-8; a Linux desktop session normally sets LANG itself.
    locale: process.platform === 'darwin' ? terminalLocale(app.getPreferredSystemLanguages()) : 'C.UTF-8' };
  if (local) env = shellKind === 'zsh' ? zshEnvironment(env, integration) : shellEnvironment(env, integration);
  const sshAskpassPath = project.kind === 'ssh' ? prepareAskpass() : undefined;
  const terminal = project.kind === 'ssh' ? new RemoteConnection({ ...project, id }, { integrationDir, auth: sshAuth, sessionKey, onEvent, codingPath: startPath, askpassPath: sshAskpassPath,
    onReady: info => { remoteBranch(project.id, info.branch); },
  }) : shellKind === 'zsh' ? pty.spawn(shell.file, ['-l', '-i'], {
    name: 'xterm-256color', cols: 90, rows: 22, cwd: startPath, env,
  }) : shellKind === 'bash' ? pty.spawn(shell.file, bashArguments(integrationDir), {
    name: 'xterm-256color', cols: 90, rows: 22, cwd: startPath, env,
  }) : shellKind === 'cmd' ? pty.spawn(cmdPath, ['/D', '/Q', '/K', path.join(integrationDir, 'bootstrap.cmd')], {
    name: 'xterm-256color', cols: 90, rows: 22, cwd: startPath, env, useConpty: true, useConptyDll: true,
  }) : pty.spawn(powershellPath, ['-NoLogo', '-NoProfile', '-NoExit', '-ExecutionPolicy', 'Bypass', '-File', path.join(integrationDir, 'bootstrap.ps1')], {
    name: 'xterm-256color', cols: 90, rows: 22, cwd: startPath, env, useConpty: true, useConptyDll: true,
  });
  const s = {
    terminal, terminalId: id, projectId: project.id, sessionId, sessionKey, bootstrapFile, status: 'starting', ready: false, shellKind,
    // Command Prompt reports its prompts through markers in its output instead of the event pipe.
    prompts: shellKind === 'cmd' ? new PromptMarkers() : null,
    tools: shellKind === 'cmd' ? { codex: onPath('codex', env), claude: onPath('claude', env) } : null,
    titles: new TerminalTitleTracker(), reportedThreadId: null,
    codexActive: false, codexAvailable: null, seq: 0, chunks: [], bytes: 0, pending: '',
    flushTimer: null, error: null, submissions: new SubmissionTracker(),
  };
  s.actions = new ActionLog(change => publishAction(s, change));
  s.gate = new InputGate(data => { if (sessions.get(id) === s && s.status !== 'exited') terminal.write(data); }, { shellOwnsInput: () => !s.codexActive });
  s.promptQueue = new PromptQueue(() => { if (sessions.get(id) === s) scheduleState(); });
  // A prompt the agent's own record shows it received is being worked on. History read when a session is
  // resumed is older than the agent's start and is left out.
  s.conversation = new ConversationLog(change => {
    publishConversation(s, change);
    const entry = change.entry;
    if (entry?.role === 'user' && s.codexActive && entry.at >= (s.activitySince || 0) - 1000) s.promptQueue.start(entry.text, entry.at, entry.id);
  });
  sessions.set(id, s);
  store.setRestore(id, { terminal: true, ...(restorePlans.has(id) ? {} : { codex: false }) });
  startupErrors.delete(id);
  const flush = () => {
    clearTimeout(s.flushTimer); s.flushTimer = null;
    if (!s.pending) return;
    send('terminal:data', { id, sessionId, seq: ++s.seq, data: s.pending });
    s.pending = '';
  };
  s.flush = flush;
  terminal.onData(data => {
    if (sessions.get(id) !== s) return;
    if (s.prompts) for (const cwd of s.prompts.write(data)) {
      onEvent({ projectId: id, sessionKey, type: 'shell-prompt', sequence: (s.lastShellEventSequence || 0) + 1, cwd, codexAvailable: s.tools.codex, claudeAvailable: s.tools.claude,
        codexHome: env.CODEX_HOME || path.join(os.homedir(), '.codex') });
    }
    for (const threadId of s.titles.write(data)) {
      if (s.reportedThreadId !== threadId) {
        s.reportedThreadId = threadId;
        if (s.codexActive) { s.codexActivity = 'unknown'; s.activityInputAt = 0; store.setRestore(id, { threadId }); void s.activityMonitor?.poll(); }
      }
    }
    s.gate.output(data);
    s.chunks.push(data); s.bytes += data.length; s.pending += data;
    while (s.bytes > 1024 * 1024 && s.chunks.length > 1) s.bytes -= s.chunks.shift().length;
    if (s.pending.length > 65536) flush();
    else if (!s.flushTimer) s.flushTimer = setTimeout(flush, 16);
  });
  terminal.onExit(({ exitCode }) => {
    if (sessions.get(id) !== s) return;
    flush();
    s.status = 'exited'; s.ready = false; s.codexActive = false;
    s.activityMonitor?.stop(); s.activityMonitor = null; s.codexActivity = 'unknown';
    restorePlans.delete(id);
    if (exitCode) s.error = terminal.error || t('终端已退出（代码 {code}）。', { code: exitCode });
    if (!quitting && !exitCode) store.setRestore(id, { terminal: false, codex: false });
    if (bootstrapFile) fs.rmSync(bootstrapFile, { force: true });
    broadcast();
  });
  captureBranch(project);
  broadcast();
}

// Codex connected directly (Settings › 编码助手): no shell and no screen to read. Its app-server reports the
// conversation, the steps and when a round starts and ends; the session keeps the fields a terminal's agent has, so
// the lights, the activity pane, completion alerts and restoring work the same.
function startDirect(id, threadId = store.findTerminal(id)?.record.restore?.threadId || null) {
  const project = findProject(id);
  if (project.kind === 'ssh') throw new Error('SSH 项目暂不支持 Codex 直连。');
  const old = sessions.get(id);
  if (old && old.status !== 'exited') return;
  if (old) disposeTerminal(id);
  if (!fs.existsSync(project.path)) throw new Error('项目目录不存在，请重新添加。');
  const cwd = store.findTerminal(id)?.record.restore?.cwd || project.path;
  const s = { terminalId: id, projectId: project.id, sessionId: randomUUID(), status: 'starting', ready: true, direct: true, shellKind: 'codex',
    codexActive: true, agent: 'codex', codexActivity: 'unknown', activitySince: Date.now(), activityInputAt: 0, card: null, info: {},
    seq: 0, chunks: [], bytes: 0, flush() {}, error: null, submissions: new SubmissionTracker(), gate: { input() {}, output() {}, dispose() {} } };
  s.actions = new ActionLog(change => publishAction(s, change));
  s.promptQueue = new PromptQueue(() => { if (sessions.get(id) === s) scheduleState(); });
  s.conversation = new ConversationLog(change => {
    publishConversation(s, change);
    const entry = change.entry;
    if (entry?.role === 'user' && entry.at >= s.activitySince - 1000) s.promptQueue.start(entry.text, entry.at, entry.id);
    if (entry?.role === 'assistant' && entry.text) noteReply(s, { text: entry.text });
  });
  const live = () => sessions.get(id) === s;
  s.codex = new CodexDirect({ cwd, env: createTerminalEnvironment(withoutAppImage(process.env), ''), conversation: s.conversation, actions: s.actions, version: app.getVersion(),
    turn: (state, turnId) => {
      if (!live()) return;
      if (state !== 'working') s.promptQueue.finish(Date.now());
      applyActivity(project, s, { threadId: s.codex.threadId, turnId: state === 'complete' ? turnId : null, state, updatedAt: Date.now(), prompt: s.lastPrompt });
    },
    card: card => { if (!live()) return; s.card = card; s.needsInput = card ? { message: card.kind === 'question' ? t('等待你回答问题') : t('等待你确认'), since: Date.now() } : null; broadcast(); },
    info: info => {
      if (!live()) return;
      s.info = { ...s.info, ...info };
      if (info.threadId) store.setRestore(id, { codex: true, direct: true, threadId: info.threadId });
      scheduleState();
    },
    exit: error => { if (!live() || s.status === 'exited') return; s.status = 'exited'; s.codexActive = false; s.codexActivity = 'unknown'; s.card = null; s.error = quitting ? null : error?.message || null; broadcast(); } });
  s.terminal = { write() {}, resize() {}, kill: () => s.codex.dispose() };
  sessions.set(id, s);
  store.setRestore(id, { terminal: true, codex: true, direct: true });
  startupErrors.delete(id);
  s.codex.start(threadId).then(() => { if (live()) { s.status = 'shell'; broadcast(); } }, error => {
    if (!live()) return;
    s.status = 'exited'; s.codexActive = false; s.error = t('无法启动 Codex 直连：{message}', { message: error.message }); s.codex.dispose(); broadcast();
  });
  captureBranch(project);
  broadcast();
}
// A terminal remembered as Codex connected directly comes back that way while the setting is on.
function startSession(id) {
  const restore = store.findTerminal(id)?.record.restore;
  return store.settings.codexDirect && restore?.direct ? startDirect(id) : startTerminal(id);
}

function disposeTerminal(id) {
  const s = sessions.get(id);
  if (!s) return;
  sessions.delete(id);
  clearTimeout(s.flushTimer); clearTimeout(s.actionTimer); clearTimeout(s.conversationTimer);
  for (const timer of s.submissionPolls || []) clearTimeout(timer);
  s.activityMonitor?.stop(); s.gate.dispose(); s.promptQueue.reset();
  try { s.terminal.kill(); } catch { }
  if (s.bootstrapFile) fs.rmSync(s.bootstrapFile, { force: true });
}

// always: ask even with nothing running (removing a project by its shortcut).
async function confirmTerminalClose(id, verb, all = false, always = false) {
  const project = findProject(id);
  const chosen = all ? [...sessions.values()].filter(item => item.projectId === project.id) : [sessions.get(id)].filter(Boolean);
  const count = chosen.filter(item => item.status !== 'exited').length;
  if (!count && !always) return true;
  const result = await dialog.showMessageBox(window, {
    type: 'question', title: t(`${verb}${all ? '项目' : '终端'}`),
    message: count ? t('{verb}“{name}”的 {count} 个终端？', { verb: t(verb), name: project.name, count }) : t('移除项目“{name}”？', { name: project.name }),
    detail: count ? t('所选终端内的 Codex 和其他运行中的命令会被结束。项目文件会保留。') : t('项目文件会保留，以后可以重新添加。'),
    buttons: [t('取消'), t(`确认${verb}`)], defaultId: 0, cancelId: 0,
  });
  return result.response === 1;
}

async function requestQuit() {
  if (!await allowEditorClose()) return false;
  const count = [...sessions.values()].filter(s => s.status !== 'exited').length;
  if (count) {
    const result = await dialog.showMessageBox(window, {
      type: 'question', message: t('退出并关闭 {count} 个终端？', { count }),
      detail: t('运行中的任务会被结束。若要让任务继续，请最小化窗口或关闭到系统托盘。'),
      buttons: [t('继续运行'), t('退出应用')], defaultId: 0, cancelId: 0,
    });
    if (result.response !== 1) return false;
  }
  quitting = true;
  app.quit();
  return true;
}

function registerIpc() {
  const { handle, listen } = createIpcAdapter({ ipcMain, getWindow: () => window, devUrl, t, report });
  registerAgentsIpc({ handle, agents, openExternal: url => shell.openExternal(url), getSession: id => sessions.get(id), findProject,
    getRestoreCwd: id => store.findTerminal(id)?.record.restore?.cwd, listClaudeSessions, followClaudeSession, listAgentCommands, t });
  registerSshIpc({ handle, getSSHInfo, sshAuth, addSSH: input => store.addSSH(input), hasSession: id => sessions.has(id), getSession: id => sessions.get(id),
    startTerminal, setStartupError: (id, message) => startupErrors.set(id, message), broadcast });
  updatesIpc = registerUpdatesIpc({ handle, updateManager, openExternal: url => shell.openExternal(url), getWindow: () => window, dialog, t,
    allowEditorClose, liveTerminalCount: () => [...sessions.values()].filter(session => session.status !== 'exited').length, setQuitting: value => { quitting = value; } });
  registerWorkspaceIpc({ handle, publicState, dialog, getWindow: () => window, t, addProject: (folder, name) => store.add(folder, name), getRecentProjects: () => store.recentProjects(), existsSync: fs.existsSync,
    getRecentEntry: folder => store.recentEntry(folder), forgetRecent: folder => store.forget(folder), clearHistory: () => store.clearHistory(),
    getEditorFile, allowEditorClose, confirmTerminalClose, disposeProjectTerminals, findProject, closeProjectPreviews: id => previewResources.closeProject(id),
    removeProject: id => store.remove(id), forgetBranch, broadcast, acknowledgeProject: id => store.acknowledge(id), reorderProjects: ids => store.reorderProjects(ids),
    getSettings: () => store.settings, updateStoreSettings: patch => store.updateSettings(patch),
    rebuildMenus: () => { trayMenu(); if (process.platform === 'darwin') Menu.setApplicationMenu(macMenu()); },
    clearRestorePlans: () => restorePlans.clear(), chooseVoiceModel: model => voiceManager.choose(model) });
  filesIpc = registerFilesIpc({ handle, listen, findProject, remoteFor, fileOperations, clipboardWrites, clipboard, previewResources, affectsEditor, allowEditorClose, shell,
    getActiveFileTree: () => activeFileTree, setActiveFileTree: value => { activeFileTree = value; }, setActiveTerminal: value => { activeTerminal = value; }, send });
  registerGitIpc({ handle, findProject, projectGit, setBranch, affectsEditor, allowEditorClose, getWindow: () => window, dialog, t });
  registerVoiceIpc({ handle, voiceManager });
  registerNoticesIpc({ handle, speechManager, summarySecrets, agents, getSettings: () => store.settings,
    summaryDirectory: () => path.join(app.getPath('userData'), 'summaries'), fetcher: (url, options) => electronNet.fetch(url, options),
    summarizeRound, modelSummary, listModels, connection, SUMMARY_TARGETS });
  registerEditorIpc({ handle, listen });
  registerDirectIpc({ handle, findProject, getSession: id => sessions.get(id), startDirect: (id, threadId) => startDirect(id, threadId) });
  // A new project's card offers Claude Code and Codex, fresh or continuing this folder's latest conversation.
  const folderOf = id => store.findTerminal(id)?.record.restore?.cwd || findProject(id).path;
  handle('project:card', (id, file) => fileCard(findProject(id), file, folderOf(id)));
  // A picture Codex generated opens in the system's image viewer; nothing else is opened this way.
  handle('agent:open-image', async file => {
    if (!isGeneratedImage(file) || !fs.existsSync(file)) throw new Error('只能打开 Codex 生成的图片。');
    const error = await shell.openPath(file); if (error) throw new Error(error);
    return true;
  });
  handle('agent:history', id => findProject(id).kind === 'ssh' ? { claude: null, codex: null } : folderHistory(folderOf(id)));
  handle('agent:launch', async (id, agent, mode) => {
    const project = findProject(id);
    if (!['claude', 'codex'].includes(agent)) throw new Error('无效的助手。');
    if (project.kind === 'ssh') throw new Error('SSH 项目请先启动终端，再在终端里运行助手。');
    const history = mode === 'continue' ? (await folderHistory(folderOf(id)))[agent] : null;
    launchPlans.set(id, { agent, command: launchCommand(agent, history), threadId: history?.id || null });
    startTerminal(id); broadcast(); return true;
  });
  registerTerminalIpc({ handle, listen, findProject, getSession: id => sessions.get(id), hasSession: id => sessions.has(id), startTerminal: startSession,
    addTerminal: id => store.addTerminal(id), removeTerminal: id => store.removeTerminal(id), confirmTerminalClose, forgetRestorePlan: id => restorePlans.delete(id),
    disposeTerminal, clearStartupError: id => startupErrors.delete(id), broadcast, getProjectById: id => store.projects.find(p => p.id === id),
    acknowledgeProject: id => store.acknowledge(id), expectCompletion: id => store.expectCompletion(id), scheduleState, warmSpeech, applyActivity, pollAfterSubmission, send,
    getActiveTerminal: () => activeTerminal, setActiveTerminal: value => { activeTerminal = value; }, setActiveFileTree: value => { activeFileTree = value; } });
  registerClipboardIpc({ handle, clipboardWrites, clipboard });
  registerWindowIpc({ handle, listen, getWindow: () => window, requestQuit });
}

if (!app.requestSingleInstanceLock()) {
  console.log(`Agentrix is already running with the profile ${app.getPath('userData')}; its window was brought to the front.`);
  app.quit();
} else {
  app.on('second-instance', () => showWindow());
  // Clicking the Dock icon brings back a window that was closed to the menu bar.
  app.on('activate', () => showWindow());
  app.whenReady().then(async () => {
    fs.mkdirSync(app.getPath('userData'), { recursive: true });
    // Before any terminal or agent starts: they inherit the system proxy only through process.env.
    await adoptSystemProxy({ session: electronSession.defaultSession }).catch(error => console.warn('System proxy:', error.message));
    let shellIcon = path.join(root, 'assets/icon.ico');
    if (process.platform === 'win32') shellIcon = materializeIcon(shellIcon, app.getPath('userData'));
    if (process.platform === 'win32' && installed && !process.env.AGENTRIX_DATA_DIR) {
      try {
        const repaired = repairShortcuts({ shell, executable: process.execPath, iconSource: shellIcon, userData: app.getPath('userData'),
          programs: path.join(app.getPath('appData'), 'Microsoft/Windows/Start Menu/Programs'),
          commonPrograms: process.env.ProgramData ? path.join(process.env.ProgramData, 'Microsoft/Windows/Start Menu/Programs') : null,
          desktop: app.getPath('desktop'), commonDesktop: process.env.PUBLIC ? path.join(process.env.PUBLIC, 'Desktop') : null,
        });
        shellIcon = repaired.icon;
        if (repaired.changes.length) execFile(path.join(process.env.SystemRoot || 'C:\\Windows', 'System32/ie4uinit.exe'), ['-show'], { windowsHide: true, timeout: 5000 }, () => {});
      } catch (error) { console.warn('Windows shortcut repair:', error.message); }
    }
    if (process.platform === 'win32' && app.isPackaged && !process.env.AGENTRIX_DATA_DIR) {
      try {
        const refreshed = refreshSearchIcons({ localAppData: process.env.LOCALAPPDATA, userData: app.getPath('userData'), iconSource: shellIcon });
        if (refreshed.changes.length) execFile(path.join(process.env.SystemRoot || 'C:\\Windows', 'System32/ie4uinit.exe'), ['-show'], { windowsHide: true, timeout: 5000 }, () => {});
      } catch (error) { console.warn('Windows Search icon refresh:', error.message); }
    }
    if (process.platform === 'darwin' || process.platform === 'linux') {
      zshStartup = prepareZshStartup(path.join(app.getPath('userData'), 'zsh'), integrationDir);
      // Started from the Dock or a desktop launcher, this process may have only the system PATH; codex, claude and
      // npm are found with the login shell's. Terminals build their own from the user's start-up files.
      loginShellPath(process.platform === 'linux' ? { shell: process.env.SHELL || findShell('bash') || '/bin/bash', env: withoutAppImage(process.env) } : undefined).then(value => { if (value) process.env.PATH = mergePath(value, process.env.PATH); agents.changed(); }).catch(() => {});
    }
    store = new WorkspaceStore(path.join(app.getPath('userData'), 'workspace.json'));
    summarySecrets = new SecretStore(path.join(app.getPath('userData'), 'summary-keys.json'), safeStorage);
    voiceManager = new VoiceManager({ directory: voiceDirectory(), model: store.settings.voiceModel, fetcher: (url, options) => electronNet.fetch(url, options), changed: state => send('voice:state', state) });
    // Download the offline model in the background after installation so dictation works on first use.
    // Waits for startup and session restore first; isolated test profiles skip the 239 MB download.
    speechManager = new SpeechManager({ directory: voiceDirectory(), fetcher: (url, options) => electronNet.fetch(url, options), changed: state => send('speech:state', state), busy: roundsWorking });
    if (!process.env.AGENTRIX_DATA_DIR) setTimeout(() => { if (!quitting) voiceManager.prepare().catch(() => {}); }, 8000);
    // The natural voice for spoken notices downloads once, after voice input, while announcing is on.
    // Its model is loaded only while a round is being worked on (warmSpeech), not for an idle window.
    if (!process.env.AGENTRIX_DATA_DIR) setTimeout(() => { if (!quitting && store.settings.announce) speechManager.prepare().then(() => { if (roundsWorking()) return speechManager.warm(); }).catch(() => {}); }, 20000);
    fileOperations = new FileOperations({ integrationDir, cacheRoot: path.join(app.getPath('userData'), 'file-clipboard'), remote: remoteFor, clipboardWrites,
      trash: filename => shell.trashItem(filename),
      confirmDelete: async (project, paths) => (await dialog.showMessageBox(window, { type: 'question', title: t('删除文件'), message: t('删除 {count} 个文件或文件夹？', { count: paths.length }),
        detail: `${paths.slice(0, 5).join('\n')}${paths.length > 5 ? '\n…' : ''}\n\n${project.kind === 'ssh' ? t('远程文件会被永久删除。') : t('本地文件会移入回收站。')}`,
        buttons: [t('取消'), t('删除')], defaultId: 0, cancelId: 0 })).response === 1,
      progress: value => filesIpc.setProgress(value),
    });
    runtimeDir = fs.mkdtempSync(path.join(app.getPath('userData'), 'runtime-'));
    eventServer = await createEventServer(onEvent);
    sshAuth = await new SSHAuthServer(queue => send('ssh:auth-changed', queue)).start();
    updateManager = new UpdateManager({
      updater: isInstalledBuild(app.isPackaged, process.execPath) ? require('electron-updater').autoUpdater : null,
      version: app.getVersion(), onChange: state => {
        updatesIpc?.onStateChange(state);
        send('updates:changed', state);
      },
    });
    protocol.handle('agentrix', request => {
      const url = new URL(request.url);
      if (url.host !== 'app') return new Response('Not found', { status: 404 });
      const relative = decodeURIComponent(url.pathname).replace(/^\/+/, '') || 'index.html';
      const resolved = path.resolve(root, 'dist', relative);
      if (!resolved.startsWith(path.resolve(root, 'dist') + path.sep)) return new Response('Forbidden', { status: 403 });
      return electronNet.fetch(pathToFileURL(resolved).toString());
    });
    protocol.handle('project-preview', async request => {
      if (!['GET', 'HEAD'].includes(request.method)) return new Response('Method not allowed', { status: 405 });
      try {
        const resource = await previewResources.resolve(request.url);
        return resourceResponse(resource, request);
      } catch { return new Response(t('文件不存在、超出项目范围，或预览已关闭。'), { status: 404, headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' } }); }
    });
    registerIpc();
    desktopGlassWindow = store.settings.surface === 'glass' && store.settings.glassBackground === 'desktop' && !!desktopGlassBackend;
    window = new BrowserWindow({
      width: 1500, height: 940, minWidth: 820, minHeight: 560,
      title: t('Agentrix'), backgroundColor: '#101216',
      ...(desktopGlassWindow ? desktopGlassOptions(desktopGlassBackend) : {}),
      // macOS keeps its own window buttons over the title bar; Windows draws them in the page.
      ...(process.platform === 'darwin' ? { titleBarStyle: 'hidden', trafficLightPosition: { x: 16, y: 12 } } : { frame: false }),
      show: false, icon: path.join(root, 'assets/icon.png'),
      webPreferences: { preload: path.join(__dirname, 'preload.cjs'), nodeIntegration: false, nodeIntegrationInSubFrames: false, contextIsolation: true, sandbox: true, spellcheck: false, backgroundThrottling: false },
    });
    if (desktopGlassWindow) {
      try { await applyDesktopGlass(window, runtimeDir, desktopGlassBackend); desktopGlassActive = true; }
      catch { window.setBackgroundColor('#101216'); }
    }
    if (process.platform === 'win32') window.setAppDetails({ appId: appUserModelId, appIconPath: shellIcon, appIconIndex: 0,
      relaunchCommand: app.isPackaged ? `"${process.execPath}"` : `"${process.execPath}" "${root}"`,
      relaunchDisplayName: process.env.AGENTRIX_DATA_DIR ? 'Agentrix Test' : !app.isPackaged ? 'Agentrix Dev' : installed ? 'Agentrix' : 'Agentrix Portable',
    });
    // Native fullscreen can temporarily mark a visible window as occluded.
    // Keep its live terminals and zoom painting; throttle only after hiding it.
    window.on('hide', () => window.webContents.setBackgroundThrottling(true));
    window.on('minimize', () => window.webContents.setBackgroundThrottling(true));
    window.on('show', () => window.webContents.setBackgroundThrottling(false));
    window.on('restore', () => window.webContents.setBackgroundThrottling(false));
    window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
    window.webContents.on('context-menu', (_event, params) => {
      if (activeTerminal || (!params.isEditable && !params.selectionText)) return;
      const items = params.isEditable ? [
        { label: t('撤销'), role: 'undo' }, { label: t('重做'), role: 'redo' }, { type: 'separator' },
        { label: t('剪切'), role: 'cut' }, { label: t('复制'), role: 'copy' }, { label: t('粘贴'), role: 'paste' }, { type: 'separator' }, { label: t('全选'), role: 'selectAll' },
      ] : [{ label: t('复制'), role: 'copy' }];
      Menu.buildFromTemplate(items).popup({ window });
    });
    // A frameless window has no Edit menu accelerators. Explicitly retain
    // standard editing shortcuts for inputs, including SSH password fields.
    window.webContents.on('before-input-event', (event, input) => {
      if (input.type !== 'keyDown' || activeTerminal || input.alt) return;
      // An app shortcut (Ctrl+Shift+N adds a project by default) reaches the window, which keeps the usual
      // editing meaning inside text boxes and runs the action elsewhere.
      if (isAppShortcut(input)) return;
      const key = input.key.toLowerCase();
      if (activeFileTree && (((input.control || input.meta) && ['a', 'c', 'v'].includes(key)) || ['delete', 'f2'].includes(key) || (key === 'insert' && (input.control || input.shift)))) return;
      let action;
      if (process.platform === 'darwin' ? input.meta : input.control || input.meta) action = { c: 'copy', x: 'cut', v: input.shift ? 'pasteAndMatchStyle' : 'paste', a: 'selectAll', z: input.shift ? 'redo' : 'undo', y: 'redo', insert: 'copy' }[key];
      else if (input.shift && key === 'insert') action = 'paste';
      if (action) { event.preventDefault(); window.webContents[action](); }
    });
    window.webContents.on('will-navigate', event => event.preventDefault());
    window.webContents.on('will-frame-navigate', event => {
      if (!event.isMainFrame && event.url !== 'about:blank' && !previewResources.hasUrl(event.url)) event.preventDefault();
    });
    const allowPlayerFullscreen = (contents, permission, details) => permission === 'fullscreen' && contents === window.webContents && details.isMainFrame === true;
    const isAppFrame = (contents, details) => contents === window.webContents && details.isMainFrame === true && (devUrl ? contents.getURL().startsWith(devUrl + '/') : contents.getURL().startsWith('agentrix://app/'));
    window.webContents.session.setPermissionRequestHandler((contents, permission, callback, details) => callback(allowPlayerFullscreen(contents, permission, details) || permission === 'media' && isAppFrame(contents, details) && details.mediaTypes?.length > 0 && details.mediaTypes.every(type => type === 'audio')));
    window.webContents.session.setPermissionCheckHandler((contents, permission, _origin, details) => allowPlayerFullscreen(contents, permission, details) || permission === 'media' && isAppFrame(contents, details) && details.mediaType === 'audio');
    window.once('ready-to-show', () => window.show());
    window.on('focus', () => { clearTimeout(attentionTimer); window.flashFrame(false); });
    window.on('enter-full-screen', () => send('window:fullscreen-changed', true));
    window.on('leave-full-screen', () => send('window:fullscreen-changed', false));
    // The reason (crashed, oom, killed…) and exit code are kept in the log before the window loads again.
    window.webContents.on('render-process-gone', (_event, details) => {
      console.error(`Window renderer gone: ${JSON.stringify({ reason: details.reason, exitCode: details.exitCode, terminalRenderer: store.settings.terminalRenderer })}`);
      if (!quitting && details.reason !== 'clean-exit') window.reload();
    });
    window.on('close', event => {
      if (quitting) return;
      event.preventDefault();
      if (store.settings.closeToTray && tray) window.hide();
      else requestQuit().catch(report);
    });
    tray = new Tray(trayImage('icon.png'));
    tray.setToolTip(t('Agentrix'));
    trayMenu();
    tray.on('click', () => showWindow());
    Menu.setApplicationMenu(process.platform === 'darwin' ? macMenu() : null);
    for (const project of store.projects) captureBranch(project);
    await window.loadURL(devUrl || 'agentrix://app/index.html');
    updateIndicators();
    if (!process.env.AGENTRIX_DATA_DIR) updateManager.start();
    if (store.settings.restoreSessions && (!process.env.AGENTRIX_DATA_DIR || process.env.AGENTRIX_TEST_RESTORE === '1')) {
      const terminals = store.projects.flatMap(project => [project, ...(project.terminals || [])].filter(record => record.restore === null || record.restore?.terminal));
      terminals.forEach((record, index) => {
        if (record.restore === null || record.restore.codex) restorePlans.set(record.id, { codex: record.restore?.codex === true, cwd: record.restore?.cwd });
        const timer = setTimeout(() => {
          if (quitting || !store.settings.restoreSessions || !store.findTerminal(record.id) || record.restore?.terminal === false) return;
          try { startSession(record.id); } catch (error) { restorePlans.delete(record.id); startupErrors.set(record.id, error.message); broadcast(); }
        }, index * 300);
        timer.unref?.();
      });
    }
  }).catch(error => {
    dialog.showErrorBox('Agentrix 无法启动', String(error?.stack || error));
    app.exit(1);
  });
}
app.on('before-quit', event => {
  // On macOS the Dock's Quit and logging out reach here directly; they ask about running terminals like ⌘Q.
  if (process.platform === 'darwin' && !quitting && window && !window.isDestroyed()) { event.preventDefault(); showWindow(); requestQuit().catch(report); return; }
  clearTimeout(attentionTimer);
  voiceManager?.close(); speechManager?.close(); fileOperations?.cancel();
  quitting = true;
  updateManager?.dispose();
  clearTimeout(stateTimer);
  for (const id of sessions.keys()) disposeTerminal(id);
  sshAuth?.close();
  eventServer?.close();
  tray?.destroy();
  cleanupAskpass();
  if (runtimeDir) {
    // Only this launch's generated, now-empty runtime directory is removed.
    try { fs.rmdirSync(runtimeDir); } catch { }
  }
});
app.on('window-all-closed', () => { if (quitting) app.quit(); });
