import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { _electron as electron } from 'playwright-core';
import { waitFor } from './wait.mjs';
import { testRun } from './test-output.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),require=createRequire(import.meta.url);
const monoTheme=process.env.AGENTRIX_MONO_THEME === 'mono-amber-dark' ? 'mono-amber-dark' : 'mono-amber';
const output=await testRun(monoTheme === 'mono-amber-dark' ? 'monochrome-dark' : 'monochrome'),profile=path.join(output,'profile'),home=path.join(output,'codex-home');
const names=['界面开发','发布检查','文件与 Git'];
const projects=names.map((name,index)=>({id:randomUUID(),name,path:path.join(output,name),kind:'local',unread:index===1?1:0,lastCompletedAt:index===1?Date.now()-60000:null,restore:{terminal:false,codex:false}}));
for(const dir of [profile,path.join(home,'sessions'),...projects.map(p=>p.path)])await fs.mkdir(dir,{recursive:true});
const markdown='# 简洁，但保留信息\n\n黑白承担阅读，橙色表示需要关注。\n\n## 工作区说明\n\n- 文字保持清晰，不随背景变透明。\n- 使用 **粗体**、层级和留白建立重点。\n- Git 仍有 `+ / −` 与状态字母。\n\n```ts\nconst needsAttention = unread || waitingForInput;\n```\n\n| 内容 | 表达 |\n| --- | --- |\n| 正常工作 | 中性色 |\n| 等待查看 | 橙色提示 |\n';
for(const p of projects)await fs.writeFile(path.join(p.path,'README.md'),markdown);
const git=(...args)=>execFileSync('git',['-C',projects[2].path,...args],{windowsHide:true,stdio:'pipe'});
git('init','-b','main');git('config','user.name','Theme fixture');git('config','user.email','fixture@example.test');
await fs.writeFile(path.join(projects[2].path,'settings.ts'),'export const theme = "forest";\nexport const attention = "pink";\n');git('add','.');git('commit','-m','Initial fixture');
await fs.writeFile(path.join(projects[2].path,'settings.ts'),'export const theme = "mono-amber";\nexport const attention = "orange";\n');
await fs.writeFile(path.join(profile,'workspace.json'),JSON.stringify({version:2,projects,settings:{theme:'forest',terminalRenderer:'dom',notifications:false,sound:false,announce:false,restoreSessions:false,closeToTray:false,fontSize:14}}));
const env={...process.env,AGENTRIX_DATA_DIR:profile,AGENTRIX_TEST_TITLEBAR: '1',CODEX_HOME:home};delete env.ELECTRON_RUN_AS_NODE;delete env.AGENTRIX_DEV_URL;
let app,page;const errors=[],results={checks:[],output,profile};
const state=async()=>(await page.evaluate(()=>window.agentrix.getState())).value;
const panel=i=>page.locator(`[data-project-id="${projects[i].id}"]`);
const write=(i,data)=>page.evaluate(({id,data})=>window.agentrix.writeTerminal(id,data),{id:projects[i].id,data});
async function choose(theme){await page.evaluate(theme=>window.agentrix.settings({theme}),theme);await waitFor(()=>page.evaluate(theme=>document.documentElement.dataset.theme===theme,theme),'theme applies');}
async function capture(name){await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setFullScreen(false);w.setContentSize(1500,920);});await page.waitForTimeout(250);await page.screenshot({path:path.join(output,name)});}
async function launch(){app=await electron.launch({executablePath:require('electron'),args:[root],cwd:root,env});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await app.evaluate(({dialog,BrowserWindow})=>{dialog.showMessageBox=async()=>({response:1});BrowserWindow.getAllWindows()[0].setContentSize(1500,920);});await page.waitForSelector('.project-panel');}
try{
 await launch();await panel(0).getByRole('button',{name:'只打开终端',exact:true}).click();await waitFor(async()=>(await state()).projects[0].shellReady,'PowerShell ready');
 const session=(await state()).projects[0].sessionId;
 await write(0,"$global:shownPrompt = $function:prompt; function global:prompt { $null = & $global:shownPrompt; 'PS> ' }; Clear-Host; Write-Host 'MONOCHROME / AGENTRIX'; Write-Host ''; Write-Host 'Default text / 默认正文'; Write-Host (([string][char]27)+'[31mRED '+([string][char]27)+'[32mGREEN '+([string][char]27)+'[34mBLUE'+([string][char]27)+'[0m'); Write-Host (([string][char]27)+'[38;5;196mEXT_RED '+([string][char]27)+'[38;5;46mEXT_GREEN '+([string][char]27)+'[38;5;21mEXT_BLUE'+([string][char]27)+'[0m'); Write-Host (([string][char]27)+'[48;2;30;30;30m'+([string][char]27)+'[38;2;255;255;255mNATIVE_DARK_SURFACE'+([string][char]27)+'[0m')\r");
 await waitFor(()=>panel(0).locator('.xterm-rows').innerText().then(t=>t.includes('NATIVE_DARK_SURFACE')),'ANSI output');
 const colors=()=>panel(0).locator('.xterm-rows > div').evaluateAll(rows=>{const row=rows.find(row=>row.textContent.trim()==='RED GREEN BLUE');return row?[...row.querySelectorAll('span')].map(span=>getComputedStyle(span).color):null;});
 await waitFor(async()=>!!(await colors()),'rendered ANSI sample');
 const extendedColors=()=>panel(0).locator('.xterm-rows > div').evaluateAll(rows=>{const row=rows.find(row=>row.textContent.trim()==='EXT_RED EXT_GREEN EXT_BLUE');return row?[...row.querySelectorAll('span')].map(span=>getComputedStyle(span).color):null;});
 await waitFor(async()=>!!(await extendedColors()),'rendered extended ANSI sample');
 const originalExtended=await extendedColors();
 const original=await colors();await panel(0).locator('.terminal-host').evaluate(node=>{globalThis.originalMonoTerminal=node;});
 await write(0,"Write-Output 'THEME_DRAFT_PRESERVED'");await choose(monoTheme);
 assert.equal((await state()).projects[0].sessionId,session);assert.ok(await panel(0).locator('.terminal-host').evaluate(node=>node===globalThis.originalMonoTerminal));
 await waitFor(async()=>JSON.stringify(await colors())!==JSON.stringify(original),'terminal palette updates');results.monochromeColors=await colors();
 await waitFor(async()=>JSON.stringify(await extendedColors())!==JSON.stringify(originalExtended),'extended palette updates');
 assert.ok((await extendedColors()).every(color=>{const [r,g,b]=color.match(/\d+/g).map(Number);return r===g&&g===b;}),'extended ANSI colours are neutral');
 await choose('forest');await waitFor(async()=>JSON.stringify(await colors())===JSON.stringify(original),'original palette restored');await waitFor(async()=>JSON.stringify(await extendedColors())===JSON.stringify(originalExtended),'original extended palette restored');await choose(monoTheme);
 assert.ok((await page.evaluate(id=>window.agentrix.attachTerminal(id),projects[0].id)).value.data.includes('THEME_DRAFT_PRESERVED'));await write(0,'\x03');
 await page.evaluate(()=>window.agentrix.settings({terminalRenderer:'gpu'}));await waitFor(()=>panel(0).locator('canvas').count().then(n=>n>0),'GPU terminal');assert.equal((await state()).projects[0].sessionId,session);await capture('gpu-terminal.png');await page.evaluate(()=>window.agentrix.settings({terminalRenderer:'dom'}));await waitFor(()=>panel(0).locator('.xterm-rows').isVisible(),'DOM terminal');
 results.checks.push('GPU terminal renders without recreating its session');
 results.checks.push('theme switches preserve terminal identity, 16/256-colour ANSI text and unsent input; original colours restore');
 await page.getByRole('button',{name:'工作台设置',exact:true}).click();assert.ok(await page.getByRole('radio',{name:monoTheme === 'mono-amber-dark' ? '白黑橙' : '黑白橙',exact:true}).isChecked());await capture('settings.png');await page.getByRole('button',{name:'完成',exact:true}).click();
 await capture('overview.png');
 const signal=await panel(1).evaluate(node=>getComputedStyle(node).getPropertyValue('--signal-rgb').trim());assert.equal(signal,'255, 107, 0');
 const done=path.join(output,'task.done'),thread=randomUUID(),transcript=path.join(home,'sessions',`rollout-${thread}.jsonl`);
 const quote=value=>"'"+value.replaceAll("'","''")+"'";
 await write(0,`Send-AgentrixEvent 'codex-started'; while(-not(Test-Path -LiteralPath ${quote(done)})){Start-Sleep -Milliseconds 100}; Send-AgentrixEvent 'codex-exited'\r`);
 await waitFor(async()=>(await state()).projects[0].codexActive,'offline task starts');
 await fs.writeFile(transcript,JSON.stringify({type:'session_meta',payload:{id:thread,cwd:projects[0].path,source:'cli'}})+'\n'+JSON.stringify({type:'event_msg',timestamp:new Date().toISOString(),payload:{type:'task_started',turn_id:'monochrome-turn'}})+'\n');
 await waitFor(()=>panel(0).getAttribute('data-status').then(v=>v==='working'),'working state');
 assert.equal(await panel(0).evaluate(n=>getComputedStyle(n).getPropertyValue('--signal-rgb').trim()),monoTheme === 'mono-amber-dark' ? '241, 242, 244' : '23, 25, 29');
 await app.evaluate(({ipcMain},text)=>{ipcMain.removeHandler('terminal:conversation');ipcMain.handle('terminal:conversation',()=>({ok:true,value:[{id:'u',at:Date.now(),role:'user',text:'新增一个可选风格：黑白、透明背景和橙色提醒。'},{id:'a',at:Date.now(),role:'assistant',text}]}));},markdown);
 await panel(0).getByRole('button',{name:'全屏查看 界面开发',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.focus-motion-panel'));
 await page.getByRole('button',{name:'切换到终端',exact:true}).click();await page.getByRole('button',{name:'阅读视图：按文档排版显示对话',exact:true}).click();
 await page.locator('.reading-markdown h1').waitFor();await capture('reading.png');
 const heading=await page.locator('.reading-markdown h1').evaluate(n=>getComputedStyle(n).color);assert.equal(heading,monoTheme === 'mono-amber-dark' ? 'rgb(241, 242, 244)' : 'rgb(23, 25, 29)');
 const activityShadow=await page.locator('.activity-now').evaluate(node=>getComputedStyle(node).boxShadow);
 const channels=activityShadow.match(/rgba?\((\d+), (\d+), (\d+)/)?.slice(1).map(Number);
 assert.ok(channels && Math.max(...channels)-Math.min(...channels)<12, 'working activity keeps a neutral outline: '+activityShadow);
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setFullScreen(true));
 await page.waitForSelector('.app-shell.titlebar-auto');
 const titlebar=await page.locator('.titlebar').evaluate(node=>({background:getComputedStyle(node).backgroundColor,ink:getComputedStyle(node.querySelector('.titlebar-brand')).color}));
 assert.ok(titlebar.background.startsWith(monoTheme==='mono-amber-dark' ? 'rgba(21, 23, 26,' : 'rgba(249, 250, 251,'), 'fullscreen titlebar uses theme chrome: '+JSON.stringify(titlebar));
 assert.equal(titlebar.ink,monoTheme==='mono-amber-dark' ? 'rgb(241, 242, 244)' : 'rgb(23, 25, 29)');
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setFullScreen(false));
 results.checks.push('neutral working activity outline and readable fullscreen titlebar');
 results.checks.push('working is neutral, unread completion amber, reading headings and code are monochrome');
 await fs.writeFile(done,'done');await waitFor(async()=>(await state()).projects[0].shellReady,'offline task finishes');
 await page.getByRole('button',{name:'返回总览',exact:true}).click();await panel(2).getByRole('button',{name:'全屏查看 文件与 Git',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.focus-motion-panel'));
 await page.getByRole('button',{name:'Git 历史',exact:true}).click();await page.getByRole('button',{name:'已修改 settings.ts',exact:true}).click();
 await page.locator('.git-line-added').first().waitFor();await capture('git-diff.png');
 assert.ok(await page.locator('.git-line-added > span:nth-child(3)').first().innerText()==='+');assert.ok(await page.locator('.git-line-removed > span:nth-child(3)').first().innerText()==='-');
 await page.evaluate(()=>window.agentrix.settings({surface:'solid'}));await waitFor(()=>page.evaluate(()=>document.documentElement.dataset.surface==='solid'),'solid mode');await capture('solid-git.png');
 results.checks.push('Git additions and removals retain explicit prefixes and distinct neutral surfaces; solid mode works');
 await app.close();app=null;await launch();assert.equal((await state()).settings.theme,monoTheme);await waitFor(()=>page.evaluate(theme=>document.documentElement.dataset.theme===theme,monoTheme),'theme persists after restart');
 results.checks.push('selected theme survives restart');assert.deepEqual(errors,[]);console.log('PASS:',results.checks.join('; '));
}catch(error){if(page)await capture('failure.png').catch(()=>{});throw error;}finally{if(app)await app.close();await fs.writeFile(path.join(output,'results.json'),JSON.stringify(results,null,2));console.log('Monochrome artifacts:',output);}
